### ISSUE TITLE
nbn-mdn / nbn-hybrid param-learning scoring crashes on hybrid networks with continuous parents

### ISSUE THREAD

**Issue by Giovannibriglia** [Giovannibriglia/NeuralBayesianNetworks#68]
## Summary

`_build_param_learning_pairs_nbn` at `benchmarking/crash_test_runner.py:546`
unconditionally accesses `n_classes` on every parent mechanism when
the child node is discrete:

```python
if kind == "discrete":
    parent_cards = [bn.true_model.mechanisms[p].n_classes for p in parents]
```

This assumes all parents of a discrete child are also discrete-categorical.
On hybrid networks where a discrete child has at least one continuous (LG)
parent, the access raises `AttributeError: 'LinearGaussianMechanism' object
has no attribute 'n_classes'` and the cell crashes.

**Pre-existing issue** in the scoring code, not introduced by PR #65 itself
— but only reachable AFTER PR #65 added hybrid to `nbn-mdn` and `nbn-hybrid`'s
applicable families.  Also note: only triggers at network sizes where the
randomly-generated DAG happens to produce a discrete child with a
continuous parent.  At n=5 the synthetic BNs are small enough that this
configuration didn't appear; at n=10 it surfaces deterministically with
`torch.manual_seed(0)`.

## Reproduction

```python
import torch
from benchmarking._baseline_registry import BaselineSpec
from benchmarking._crash_test_utils import CrashTestConfig
from benchmarking.crash_test_runner import _param_learning_cell

cfg = CrashTestConfig.from_yaml(
    'benchmarking/configs/parameter_learning_smoke.yaml'
)
torch.manual_seed(0)
spec = BaselineSpec('nbn', 'mdn', 'mle')   # also reproduces with ('nbn', 'hybrid', 'mle')
rows = _param_learning_cell(cfg, 'hybrid', 10, 0, spec)
```

## Error

```
AttributeError: 'LinearGaussianMechanism' object has no attribute 'n_classes'
  File "benchmarking/crash_test_runner.py", line 546, in _build_param_learning_pairs_nbn
    parent_cards = [bn.true_model.mechanisms[p].n_classes for p in parents]
```

Full failure path:
- `_param_learning_cell` → `_fit_and_score_nbn` → `_score_param_learning_metrics_nbn`
  → `_build_param_learning_pairs_nbn:546`

The fit step succeeds; the scoring step (which builds CPD comparison pairs
between true and fitted models) is where the crash happens.

## Scope

Affected (reproduced at n=10 hybrid, seed 0):
- `nbn-mdn` (param-learning) on hybrid
- `nbn-hybrid` (param-learning) on hybrid

Not affected:
- Same labels on `continuous_lg` / `continuous_nongauss` — pure-continuous
  families have no discrete children, so the `if kind == "discrete"` branch
  doesn't fire.
- The inference-side counterparts (`nbn-mdn-lw`, `nbn-hybrid-router`) are
  affected by a separate bug at `categorical_table.py:124` — see #69.
- `n=5`: randomly-generated DAGs at this size happen to avoid the failing
  configuration in the smoke seed.  Larger seeds at `n=5` may still hit it.

The runner's `run_with_guard` catches the crash and emits a `not_supported`
row at runtime, so CI doesn't fail hard — but the cells produce zero data
until this is fixed.

## Suggested fix direction

The scoring path needs to handle hybrid networks where a discrete child
has continuous parents.  Three candidate approaches:

1. **Filter parent_cards by parent kind**: only include parents whose
   mechanism has `n_classes` (i.e., discrete parents).  Pass a partial
   `parent_cards` list to `tabulate(...)`.  May not produce
   semantically-meaningful CPT comparison if the tabulate API requires
   the full parent set.

2. **Skip discrete-child nodes with mixed-kind parents**: emit those
   nodes' rows with `status='not_supported'` and a tractable error_msg.
   Cells become partial but don't crash.

3. **Build a separate scoring path for hybrid families**: discrete-child-
   with-continuous-parent comparison probably needs a sample-based
   approach rather than CPD enumeration.  Largest refactor; cleanest
   semantics.

The Phase 0.5 reachability investigation on PR #65 only tested at n=5,
which is insufficient to surface hybrid-DAG-shape-dependent bugs.
**Lesson**: future Pass-10 priorities should test hybrid additions at
multiple n_nodes values, not just the smallest.

## Refs

- PR #65 (Pass 10 priority-1 — promoted these cells from `_NOT_APPLICABLE`
  to applicable; pre-existing scoring bug then became reachable)
- `docs/audits/v0.8-baseline-applicability-audit.md` §7.2 (will be expanded
  to reference this issue when audit doc PR #67 lands)
- Sibling bug: nbn-*-lw inference fit crashes on hybrid n>=10 — #69
